### ISSUE TITLE
undefined method `ruby_sudo_command'

### ISSUE THREAD

**Issue by jelmerj** [erikogan/passenger#18]
Hi,

I installed your mod_passenger package on RHEL6 today, but my Rails application won't start. I get the following error in my Apache httpd error log:

[ pid=17144 thr=140450742876128 file=ext/apache2/Hooks.cpp:865 time=2011-10-10 13:26:57.940 ]: Unexpected error in mod_passenger: Cannot spawn application '/var/www/html/lunch': The spawn server has exited unexpectedly.
  Backtrace:
     in 'virtual Passenger::SessionPtr Passenger::ApplicationPool::Client::get(const Passenger::PoolOptions&)' (Client.h:750)
     in 'Passenger::SessionPtr Hooks::getSession(const Passenger::PoolOptions&)' (Hooks.cpp:297)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:566)

**\* Exception NoMethodError in spawn manager (undefined method `ruby_sudo_command' for PhusionPassenger::PlatformInfo:Module) (process 3685, thread #<Thread:0x7f6a52ac6368>):
        from (erb):10:in`result'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.9/lib/phusion_passenger/html_template.rb:63:in `layout'
        from (erb):22:in`get_binding'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.9/lib/phusion_passenger/html_template.rb:53:in `get_binding'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.9/lib/phusion_passenger/html_template.rb:61:in`layout'
        from (erb):1:in `result'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.9/lib/phusion_passenger/html_template.rb:46:in`result'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.9/lib/phusion_passenger/spawn_manager.rb:328:in `send_error_page'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.9/lib/phusion_passenger/spawn_manager.rb:279:in`handle_spawn_application'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.9/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.9/lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.9/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.9/helper-scripts/passenger-spawn-server:99

**Comment by jelmerj** [comment]
I narrowed down this problem, it happens only when i specify the "smart" spawnmethod, it doesnt happen with smart-lv2
